spring.application.name=api-gateway
server.port=8099

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring.cloud.gateway.server.webflux.routes[0].id=autentificacion
spring.cloud.gateway.server.webflux.routes[0].uri=lb://autentificacion
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=catalogo
spring.cloud.gateway.server.webflux.routes[1].uri=lb://catalogo
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/catalogo/**

spring.cloud.gateway.server.webflux.routes[2].id=carrito
spring.cloud.gateway.server.webflux.routes[2].uri=lb://carrito
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/carrito/**

spring.cloud.gateway.server.webflux.routes[3].id=pago
spring.cloud.gateway.server.webflux.routes[3].uri=lb://pago
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/pagos/**

spring.cloud.gateway.server.webflux.routes[4].id=gestionPedido
spring.cloud.gateway.server.webflux.routes[4].uri=lb://gestionpedido
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/pedido/**

spring.cloud.gateway.server.webflux.routes[5].id=cupones
spring.cloud.gateway.server.webflux.routes[5].uri=lb://cupones
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/cupones/**

spring.cloud.gateway.server.webflux.routes[6].id=certificacion
spring.cloud.gateway.server.webflux.routes[6].uri=lb://certificacion
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/certificacion/**

spring.cloud.gateway.server.webflux.routes[7].id=Referencias
spring.cloud.gateway.server.webflux.routes[7].uri=lb://Referencias
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/comentarios/**

spring.cloud.gateway.server.webflux.routes[8].id=Despacho
spring.cloud.gateway.server.webflux.routes[8].uri=lb://Despacho
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/despacho/**

spring.cloud.gateway.server.webflux.routes[9].id=reportess
spring.cloud.gateway.server.webflux.routes[9].uri=lb://reportess
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/reportes/**